# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df9110b7614a935e763101fea3f1e4f2"
name = "defent-app"
handle = "defent-app"
application_url = "https://pose-occur-typical-constant.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "prachanda-test.myshopify.com"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pose-occur-typical-constant.trycloudflare.com/auth/callback",
  "https://pose-occur-typical-constant.trycloudflare.com/auth/shopify/callback",
  "https://pose-occur-typical-constant.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
