   # Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3b25a5dad14fc8d8919c05f55c2df6f3"
name = "Defent Custom App"
handle = "defent-custom-app"
application_url = "https://defent-shopify-app-1.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "prachanda-test.myshopify.com"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://defent-shopify-app-1.onrender.com/auth/callback",
  "https://defent-shopify-app-1.onrender.com/auth/shopify/callback",
  "https://defent-shopify-app-1.onrender.com/api/auth/callback"
]

[pos]
embedded = false
